[package]
name = "kobod"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "kobod"
path = "src/main.rs"

[dependencies]
kobo-abi = { path = "../kobo-abi" }
kobo-app-store = { path = "../kobo-app-store" }
kobo-hal = { path = "../kobo-hal", default-features = false }
kobo-image = { path = "../kobo-image" }
kobo-json = { path = "../kobo-json" }
kobo-net = { path = "../kobo-net" }
jiff.workspace = true
kobo-policy = { path = "../kobo-policy" }
kobo-shell = { path = "../kobo-shell" }
kobo-profile = { path = "../kobo-profile" }
kobo-protocol = { path = "../kobo-protocol" }
kobo-text = { path = "../kobo-text" }
kobo-ui = { path = "../kobo-ui" }
p256 = { version = "0.13.2", features = ["ecdh", "ecdsa"] }
ring = "0.17"
base64 = "0.22"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
webpki-roots = "1"

[lints]
workspace = true

[features]
default = []
device-write = ["kobo-hal/device-write"]
