[package]
name = "kobo-sim"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
license.workspace = true

[dependencies]
kobo-image = { path = "../kobo-image" }
kobo-net = { path = "../kobo-net" }
jiff.workspace = true
kobo-policy = { path = "../kobo-policy" }
kobo-profile = { path = "../kobo-profile" }
kobo-shell = { path = "../kobo-shell" }
kobo-text = { path = "../kobo-text" }
kobo-protocol = { path = "../kobo-protocol" }
kobo-ui = { path = "../kobo-ui" }

[lints]
workspace = true
