[package]
name = "kobo-bomtoon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
http = "1.3"
kobo-image = { path = "../../crates/kobo-image" }
kobo-json = { path = "../../crates/kobo-json" }
kobo-sdk = { path = "../../crates/kobo-sdk" }

[lints]
workspace = true
