[package]
name = "kobo-ui"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Declarative E Ink UI, layout, and rendering primitives for Kobo applications"

[lints]
workspace = true

[dependencies]
kobo-pixels = { path = "../kobo-pixels" }
unicode-segmentation = "1.13.3"
